// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArlaIHbpx0XUT14s2WIA3AhU4fqsks_9I',
    appId: '1:281710856003:android:c4cb97b5fa141a696451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    storageBucket: 'buzlinholding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1rXkOurw7_hsFCHH0Q1K1ce9cD5L0U4',
    appId: '1:281710856003:ios:042a31b173163d9d6451f6',
    messagingSenderId: '281710856003',
    projectId: 'buzlinholding',
    storageBucket: 'buzlinholding.appspot.com',
    androidClientId: '281710856003-3pphqa1jghckq44gikeupdos199m3at2.apps.googleusercontent.com',
    iosClientId: '281710856003-punjatv9ftkdc68bvetsmcvcg3t9uhbt.apps.googleusercontent.com',
    iosBundleId: 'ca.buzlinpartner.ca',
  );
}
